In [2]:
import torch
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()

In [8]:
text = open('./data/cap1.txt', 'r').read().lower()

In [9]:
text

'muchos años después, frente al pelotón de fusilamiento, el coronel aureliano buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. el mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo. todos los años, por el mes de marzo, una familia de gitanos desarrapados plantaba su carpa cerca de la aldea, y con un grande alboroto de pitos y timbales daban a conocer los nuevos inventos. primero llevaron el imán. un gitano corpulento, de barba montaraz y manos de gorrión, que se presentó con el nombre de melquíades, hizo una truculenta demostración pública de lo que él mismo llamaba la octava maravilla de los sabios alquimistas de macedonia. fue de casa en casa arrastrando dos lingote

In [10]:
tokens = tokenizer.tokenize(text)

In [11]:
tokens[:50]

['muchos',
 'años',
 'después',
 ',',
 'frente',
 'al',
 'pelotón',
 'de',
 'fusilamiento',
 ',',
 'el',
 'coronel',
 'aureliano',
 'buendía',
 'había',
 'de',
 'recordar',
 'aquella',
 'tarde',
 'remota',
 'en',
 'que',
 'su',
 'padre',
 'lo',
 'llevó',
 'a',
 'conocer',
 'el',
 'hielo.',
 'macondo',
 'era',
 'entonces',
 'una',
 'aldea',
 'de',
 'veinte',
 'casas',
 'de',
 'barro',
 'y',
 'cañabrava',
 'construidas',
 'a',
 'la',
 'orilla',
 'de',
 'un',
 'río',
 'de']

In [12]:
len(tokens)

6293

In [13]:
min(len(x) for x in tokens)

1

In [14]:
max(len(x) for x in tokens)

16

## Bigrams

In [17]:
b = {}
for w1, w2 in zip(tokens, tokens[1:]):
    bigram = (w1, w2)
    b[bigram] = b.get(bigram, 0) + 1

In [18]:
b

{('muchos', 'años'): 3,
 ('años', 'después'): 2,
 ('después', ','): 2,
 (',', 'frente'): 1,
 ('frente', 'al'): 1,
 ('al', 'pelotón'): 2,
 ('pelotón', 'de'): 2,
 ('de', 'fusilamiento'): 2,
 ('fusilamiento', ','): 2,
 (',', 'el'): 10,
 ('el', 'coronel'): 3,
 ('coronel', 'aureliano'): 3,
 ('aureliano', 'buendía'): 4,
 ('buendía', 'había'): 2,
 ('había', 'de'): 4,
 ('de', 'recordar'): 2,
 ('recordar', 'aquella'): 1,
 ('aquella', 'tarde'): 2,
 ('tarde', 'remota'): 1,
 ('remota', 'en'): 1,
 ('en', 'que'): 12,
 ('que', 'su'): 7,
 ('su', 'padre'): 7,
 ('padre', 'lo'): 1,
 ('lo', 'llevó'): 3,
 ('llevó', 'a'): 3,
 ('a', 'conocer'): 3,
 ('conocer', 'el'): 2,
 ('el', 'hielo.'): 1,
 ('hielo.', 'macondo'): 1,
 ('macondo', 'era'): 1,
 ('era', 'entonces'): 1,
 ('entonces', 'una'): 2,
 ('una', 'aldea'): 3,
 ('aldea', 'de'): 1,
 ('de', 'veinte'): 1,
 ('veinte', 'casas'): 1,
 ('casas', 'de'): 1,
 ('de', 'barro'): 2,
 ('barro', 'y'): 1,
 ('y', 'cañabrava'): 1,
 ('cañabrava', 'construidas'): 1,
 ('construi

In [19]:
len(b)

4914

In [20]:
uniq_tokens = sorted(list(set(tokens)))

In [21]:
uniq_tokens

['!',
 '(',
 ')',
 ',',
 '.',
 '300',
 ':',
 ';',
 'a',
 'abandonado',
 'abandonados',
 'abandonar',
 'abandonaron',
 'abastecerse',
 'abejas',
 'abiertos.',
 'abnegación',
 'abriendo',
 'abrir',
 'abrió',
 'abrumados',
 'absoluta',
 'absoluto',
 'absorta',
 'absorto',
 'abuelo—',
 'acababa',
 'aceitada',
 'aceite',
 'aceites',
 'acento—',
 'aceptar',
 'acercaban',
 'acierto',
 'acompañado',
 'acompañaron',
 'acorazados',
 'acordarse',
 'activa',
 'actividad',
 'acto.',
 'actual',
 'acuerdo',
 'acumulado',
 'acuática',
 'adelante',
 'además',
 'adentrarse',
 'adiestrarlos',
 'adivinaba',
 'admiración',
 'adornadas',
 'adquirió',
 'adversas',
 'aflicción',
 'agarrándolo',
 'agobiados',
 'agotados',
 'agua',
 'aguas',
 'agujas',
 'ahora',
 'ahuyama',
 'aire',
 'ajeno',
 'al',
 'alambique',
 'alarmada',
 'alas',
 'albahaca.',
 'alborotada',
 'alboroto',
 'alborozo',
 'alcance',
 'alcanzaban',
 'alcanzar',
 'alcanzó',
 'aldea',
 'aldea.',
 'alegres',
 'alegría',
 'alejandría',
 'algo',
 'a

In [22]:
n_tokens = len(uniq_tokens)

In [92]:
N = 0.000001*torch.ones((n_tokens,n_tokens))

In [93]:
ttoi = {t:i for i,t in enumerate(uniq_tokens)}
itot = {i:t for t,i in ttoi.items()}

In [94]:
for w1, w2 in zip(tokens, tokens[1:]):
    ix1 = ttoi[w1]
    ix2 = ttoi[w2]
    N[ix1,ix2] += 1

In [95]:
n_tokens

2127

In [96]:
N[ttoi['a']].sum()

tensor(134.0021)

In [97]:
P = N.float()
P = P / P.sum(1, keepdim=True)


In [98]:
P[ttoi['abejas']].sum()

tensor(1.0000)

In [38]:
P.sum(1, keepdim=True)
# n_tokens x 1

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]])

In [39]:
P.sum(1)
# n_tokens -> 1 x n_tokens

tensor([1., 1., 1.,  ..., 1., 1., 1.])

In [41]:
P[ttoi['a']][:100]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0075, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])

In [57]:
g = torch.Generator().manual_seed(13)
# Pr[a|b]
word1 = 'al'
ix = ttoi[word1]
p = P[ix]
jx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
word2 = itot[jx]
' '.join([word1, word2])



'al caramelo'

In [99]:
g = torch.Generator().manual_seed(67)
for i in range(10):
    word = "aureliano"
    ix = ttoi[word]
    sentence = [word]
    while True:
        p = P[ix]
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        word = itot[ix]
        sentence.append(word)
        if '.' in word:
            break
    print(i, ' '.join(sentence))


0 aureliano , él le hinchaba de oro que presenciaba el suelo.
1 aureliano buendía ignoraba por entre dientes acorazados de un chaleco de júbilo al oro que emprender el dedo.
2 aureliano , la fundación de su mujer , conservó un hondo suspiro de chipre , úrsula , josé arcadio buendía al cuarto , que sólo había cambiado bajo la berenjena.
3 aureliano , y húmedo , como huevos prehistóricos.
4 aureliano buendía andaba a quien supiera interpretarlos intentar la casa recibía más insidiosa y alcanzó a la lepra en demostrar el mundo están , estuvo a las calles con aquellos animales prohibidos no había sido un hijo.
5 aureliano buendía había buscado , el niño hizo experto en épocas pasadas —según le revelara los navegantes con el ombligo movía la mesa una extensión acuática sin ningún órgano de que dotó de sus cajas originales las mulas del prodigio , se lo mantenía enredado en toda clase de aspecto holgazán , el mundo se convirtieron en virtud de cobre , el mono amaestrado que no merecía los pa

In [100]:
g = torch.Generator().manual_seed(67)
p = 1.0 * torch.ones(n_tokens) / n_tokens
for i in range(10):
    word = "los"
    ix = ttoi[word]
    sentence = [word]
    while True:
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        word = itot[ix]
        sentence.append(word)
        if '.' in word:
            break
    print(i, ' '.join(sentence))

0 los mapa condición —dijo —dijo—.
1 los aventura.
2 los tambores resonancia alcanzar gente alcanzó ella.
3 los admiración exaltó imaginación replicó tenemos impulso cetáceos desesperación silencio conjuro tormentosos incógnitos desarraigó víctima pregonando dedo.
4 los propio hacerle desapareció allá murmurar perplejo llevárselos centavo cinco reproche acompañaron esta comunidad.
5 los didáctica sencillo por marzo.
6 los extravió soleada suelo judía.
7 los limpios ) almizcle.
8 los él «nunca ; construyó tratando ordenada norte alboroto aparato maría creía caballo bloque noción pueblo doméstico consolarse dientes aldea cubierto convencida aún forzando francis intactos hijo.
9 los dieran luminosos leer ponía penas casas mirada tetas grupo estuvo llenó largas igual soledad pecado sanar.


### Likelihood

In [101]:
log_likelihood = 0
n = 0
for w1, w2 in zip(tokens, tokens[1:]):
    ix1 = ttoi[w1]
    ix2 = ttoi[w2]
    pr = P[ix1,ix2]
    log_likelihood += torch.log(pr)
    n += 1

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
nnll = nll/n
print(f'{nnll=}')


log_likelihood=tensor(-14134.1172)
nll=tensor(14134.1172)
nnll=tensor(2.2464)


In [102]:
log_likelihood = 0
n = 0

for w1, w2 in [('aureliano', 'buendía')]:
    ix1 = ttoi[w1]
    ix2 = ttoi[w2]
    pr = P[ix1,ix2]
    log_likelihood += torch.log(pr)
    n += 1

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
nnll = nll/n
print(f'{nnll=}')

log_likelihood=tensor(-0.6934)
nll=tensor(0.6934)
nnll=tensor(0.6934)


In [103]:
log_likelihood = 0
n = 0
for w1, w2 in [('aureliano', 'perplejo')]:
    ix1 = ttoi[w1]
    ix2 = ttoi[w2]
    pr = P[ix1,ix2]
    log_likelihood += torch.log(pr)
    n += 1

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
nnll = nll/n
print(f'{nnll=}')

log_likelihood=tensor(-15.8952)
nll=tensor(15.8952)
nnll=tensor(15.8952)


In [105]:
log_likelihood = 0
n = 0
for w1, w2 in zip(tokens, tokens[1:]):
    ix1 = ttoi[w1]
    ix2 = ttoi[w2]
    pr = 1.0 / n_tokens * torch.ones(1)
    log_likelihood += torch.log(pr)
    n += 1

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
nnll = nll/n
print(f'{nnll=}')

log_likelihood=tensor([-48214.3516])
nll=tensor([48214.3516])
nnll=tensor([7.6628])
